spring:
  datasource:
    url: jdbc:h2:mem:telestock;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

gemini:
  api:
    key: "AIzaSyBYNHFVySI1YJ-NlDx3715N9-ymFL4fpKM"
    model: "gemini-2.5-flash"

telegram:
  bot:
    token: "8835948729:AAHOe4zs4eTrW9IMOg9aHSStbCH1UC9lX_w"
  chat:
    id: "8798061093"
